"""
Django settings for Saas_app project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w3dfdg7qyqvp=vx(9x=ojw50fhxdpzn16!aow3!rp=*qe^pajh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['dj.2kvietnam.com', 'app.2kvietnam.com', 'localhost', '127.0.0.1', 'testserver']

# Frontend URL for email links
FRONTEND_URL = 'http://localhost:3000'  # Change in production

# CSRF Configuration - Trusted Origins for Cross-Domain Requests
CSRF_TRUSTED_ORIGINS = [
    'http://dj.2kvietnam.com',
    'https://dj.2kvietnam.com',
    'http://localhost:8005',
    'http://127.0.0.1:8005',
]

# Session Configuration
SESSION_COOKIE_SECURE = False  # Set True for HTTPS
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = False    # Set True for HTTPS
CSRF_COOKIE_HTTPONLY = True

# Application definition

SHARED_APPS = [
    # Multi-tenant core (registers management commands like migrate_schemas)
    'django_tenants',
    # Django core (shared across public + tenant schemas)
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    # Tenant metadata lives in the public schema
    'core.tenants.apps.TenantsConfig',
    # Access Module MUST be in SHARED_APPS (memberships are global, not per-tenant)
    'core.access.apps.AccessConfig',
    # Products Shared Module (ProductURL, PriceHistory, Domain in public schema)
    'services.products_shared.apps.ProductsSharedConfig',
]

TENANT_APPS = [
    # Apps that exist inside each tenant schema
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.staticfiles',
    # Authentication provider (allauth)
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    # Core Admin Module (phải load trước các modules khác)
    'core.admin_core.apps.AdminCoreConfig',
    # Identity Module
    'core.identity.apps.IdentityConfig',
    # Accounts Module (User Profiles & Preferences)
    'core.accounts.apps.AccountsConfig',
    # Business Services
    'services.products.apps.ProductsConfig',
]

# Order per django-tenants docs: shared apps first, followed by tenant apps
INSTALLED_APPS = SHARED_APPS + [app for app in TENANT_APPS if app not in SHARED_APPS]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Admin Core Security Middleware (phải ở cuối)
    'core.admin_core.infrastructure.security_middleware.AdminSecurityMiddleware',
]

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Required by django-allauth
SITE_ID = 1

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database configuration (PostgreSQL by default; allows sqlite via env override)
DB_ENGINE = os.getenv('DATABASE_ENGINE', 'django_tenants.postgresql_backend')
if DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': BASE_DIR / os.getenv('DATABASE_NAME', 'db.sqlite3'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME': os.getenv('DATABASE_NAME', 'saas_app'),
            'USER': os.getenv('DATABASE_USER', 'saas_app_dev'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD', 'Abcd-da3nd-2Nnd-23nd'),
            'HOST': os.getenv('DATABASE_HOST', '/tmp'),  # Use /tmp socket
            'PORT': os.getenv('DATABASE_PORT', '5432'),
        }
    }

# Django-tenants configuration (app_label.ModelName)
TENANT_MODEL = 'tenants.Tenant'
TENANT_DOMAIN_MODEL = 'tenants.TenantDomain'
DATABASE_ROUTERS = ['django_tenants.routers.TenantSyncRouter']


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================
# Email Configuration
# ============================================================
# For development: console backend (prints emails to console)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@2kvietnam.com'
EMAIL_SUBJECT_PREFIX = '[PriceSynC] '

# For production, use SMTP:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'

# ============================================================
# Logging Configuration
# ============================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# ============================================================
# Admin Core Settings
# ============================================================

# Disable hash validation in development (set True in production)
ADMIN_ENABLE_HASH = False

# Admin hash service will be initialized in apps.py
# ADMIN_HASH_SERVICE will be set there
